# Generated by Django 3.2.8 on 2021-10-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_total_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Total_downloads',
        ),
    ]
