# Generated by Django 3.2.8 on 2021-10-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug2',
            field=models.CharField(default='ygh', max_length=7),
            preserve_default=False,
        ),
    ]
