# Generated by Django 3.2.8 on 2021-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_slug',
            name='slug',
            field=models.CharField(max_length=56),
        ),
    ]
