# Generated by Django 3.2.8 on 2021-10-22 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_book_slug_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Slug',
            new_name='BookSlug',
        ),
    ]
