# Generated by Django 3.2.8 on 2021-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
