# Generated by Django 3.2.8 on 2021-10-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211027_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='file',
            new_name='image',
        ),
    ]
