# Generated by Django 3.2.8 on 2021-10-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211027_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
